
const products = [


  {
    name: "apple",
    slug: "apple",
    img: "/images/apple.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 500,
    ratings: 4.5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "banana",
    slug: "banana",
    img: "/images/banana.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 120,
    ratings: 4.5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "berries",
    slug: "berries",
    img: "/images/berries.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 80,
    ratings: 4.5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "black grapes",
    slug: "black_grapes",
    img: "/images/black_grapes.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 80,
    ratings: 4.5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "figs",
    slug: "figs",
    img: "/images/figs.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 50,
    ratings: 4.5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "green grapes",
    slug: "green_grapes",
    img: "/images/green_grapes.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 50,
    ratings: 4.5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "mango",
    slug: "mango",
    img: "/images/mango.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 900,
    ratings: 4.5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "orange",
    slug: "orange",
    img: "/images/oranges.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 100,
    ratings: 4.5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "papaya",
    slug: "papaya",
    img: "/images/papaya.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 100,
    ratings: 4.5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "pears",
    slug: "pears",
    img: "/images/pears.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 150,
    ratings: 4.5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "pomegranate",
    slug: "pomegranate",
    img: "/images/pomegranate.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 90,
    ratings: 4.5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "strawberry",
    slug: "strawberry",
    img: "/images/strawberry.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 90,
    ratings: 4.5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "watermelon",
    slug: "watermelon",
    img: "/images/watermelon.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 70,
    ratings: 4.5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "apricots",
    slug: "apricots",
    img: "/images/apricots.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 70,
    ratings: 5,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "feijoas",
    slug: "feijoas",
    img: "/images/feijoas.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 50,
    ratings: 4,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "butternut Squash",
    slug: "butternut_Squash",
    img: "/images/butternut_Squash.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 100,
    ratings: 4,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "avocado",
    slug: "avocado",
    img: "/images/avocado.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 150,
    ratings: 4,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "green mangoes",
    slug: "green_mangoes",
    img: "/images/green_mangoes.jpg",
    category: "fruits",
    description: "fruit is 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is or you can make juice",
    price: 550,
    ratings: 4,
    brand: "Cosmic Fruits",
    inStock: 20,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "tomato",
    slug: "tomato",
    img: "/images/tomato.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before eating, you can eat as it is, you can make juice or you can you it in your daily meals",
    price: 300,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 100,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "potato",
    slug: "potato",
    img: "/images/potato.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before eating,you can make curry and more",
    price: 250,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 100,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "green beans",
    slug: "green_beans",
    img: "/images/green_beans.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before eating,you can make curry and more",
    price: 200,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 100,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "Green Chilli",
    slug: "green_chilli",
    img: "/images/green_chilli.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before use,you can use in your daily foods",
    price: 100,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 100,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "Green Peas",
    slug: "green_peas",
    img: "/images/green_peas.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before use,you can use in your daily foods",
    price: 180,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 100,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "carrots",
    slug: "carrots",
    img: "/images/carrots.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before use,you can use in your daily foods",
    price: 240,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 100,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "broccoli",
    slug: "broccoli",
    img: "/images/broccoli.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before use,you can use in your daily foods",
    price: 140,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 100,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "onion",
    slug: "onion",
    img: "/images/onion.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before use,you can use in your daily foods",
    price: 200,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 100,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "leeks",
    slug: "leeks",
    img: "/images/leeks.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before use,you can use in your daily foods",
    price: 40,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 110,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "Spinach",
    slug: "spinach",
    img: "/images/spinach.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before use,you can use in your daily foods",
    price: 130,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 100,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "cauliflower",
    slug: "cauliflower",
    img: "/images/cauliflower.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before use,you can use in your daily foods",
    price: 140,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 100,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "red chilli",
    slug: "red_chilli",
    img: "/images/red_chilli.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before use,you can use in your daily foods",
    price: 140,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 100,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "cabbage",
    slug: "cabbage",
    img: "/images/cabbage.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before use,you can use in your daily foods",
    price: 140,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 100,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "cucumber",
    slug: "cucumber",
    img: "/images/cucumber.jpg",
    category: "vegetables",
    description: "vegetables are 100% natural, no chemicals used, wash with clean water before use,you can use in your daily foods",
    price: 140,
    ratings: 5,
    brand: "Cosmic Vegetables",
    inStock: 100,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "rib eye steak",
    slug: "rib_eye_steak",
    img: "/images/rib_eye_steak.jpg",
    category: "meat",
    description: "meat is 100% natural, no chemicals used, wash with clean water before use, you can use in your daily foods",
    price: 500,
    ratings: 5,
    brand: "Cosmic Meat and More",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "Red Meat",
    slug: "red_meat",
    img: "/images/red_meat.jpg",
    category: "meat",
    description: "meat is 100% natural, no chemicals used, wash with clean water before use, you can use in your daily foods",
    price: 800,
    ratings: 5,
    brand: "Cosmic Meat and More",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "raw chicken",
    slug: "raw_chicken",
    img: "/images/raw_chicken.jpg",
    category: "meat",
    description: "chicken is 100% natural, no chemicals used, wash with clean water before use, you can use in your daily foods",
    price: 800,
    ratings: 5,
    brand: "Cosmic Meat and More",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "raw chicken leg",
    slug: "raw_chicken_leg",
    img: "/images/raw_chicken_leg.jpg",
    category: "meat",
    description: "chicken is 100% natural, no chemicals used, wash with clean water before use, you can use in your daily foods",
    price: 300,
    ratings: 5,
    brand: "Cosmic Meat and More",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "raw chicken breast",
    slug: "raw_chicken_breast",
    img: "/images/raw_chicken_breast.jpg",
    category: "meat",
    description: "chicken is 100% natural, no chemicals used, wash with clean water before use, you can use in your daily foods",
    price: 300,
    ratings: 5,
    brand: "Cosmic Meat and More",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "Brown Eggs",
    slug: "brown_eggs",
    img: "/images/brown_eggs.jpg",
    category: "meat",
    description: "chicken is 100% natural, no chemicals used, wash with clean water before use, you can use in your daily foods",
    price: 300,
    ratings: 5,
    brand: "Cosmic Meat and More",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "white eggs",
    slug: "white_eggs",
    img: "/images/white_eggs.jpg",
    category: "meat",
    description: "chicken is 100% natural, no chemicals used, wash with clean water before use, you can use in your daily foods",
    price: 300,
    ratings: 5,
    brand: "Cosmic Meat and More",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "milk",
    slug: "milk",
    img: "/images/milk.jpg",
    category: "dairy",
    description: "milk is 100% natural, no chemicals used, you can use in your daily foods",
    price: 100,
    ratings: 5,
    brand: "Cosmic Dairy",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "cheese",
    slug: "cheese",
    img: "/images/cheese.jpg",
    category: "dairy",
    description: "cheese is 100% natural, no chemicals used, you can use in your daily foods",
    price: 150,
    ratings: 5,
    brand: "Cosmic Dairy",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "white bread",
    slug: "white_bread",
    img: "/images/white_bread.jpg",
    category: "dairy",
    description: "white_bread is 100% natural, no chemicals used, you can use in your daily foods",
    price: 150,
    ratings: 3,
    brand: "Cosmic Dairy",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "butter",
    slug: "butter",
    img: "/images/butter.jpg",
    category: "dairy",
    description: "butter is 100% natural, no chemicals used, you can use in your daily foods",
    price: 300,
    ratings: 4,
    brand: "Cosmic Dairy",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "yogurt",
    slug: "yogurt",
    img: "/images/yogurt.jpg",
    category: "dairy",
    description: "yogurt is 100% natural, no chemicals used, you can use in your daily foods",
    price: 150,
    ratings: 4,
    brand: "Cosmic Dairy",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "paneer",
    slug: "paneer",
    img: "/images/paneer.jpg",
    category: "dairy",
    description: "paneer is 100% natural, no chemicals used, you can use in your daily foods",
    price: 150,
    ratings: 4,
    brand: "Cosmic Dairy",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
  {
    name: "tofu",
    slug: "tofu",
    img: "/images/tofu.jpg",
    category: "dairy",
    description: "tofu is 100% natural, no chemicals used, you can use in your daily foods",
    price: 150,
    ratings: 4,
    brand: "Cosmic Dairy",
    inStock: 40,
    instruction: "store in cold place",
    quantity: 1
  },
];

export default products;
